'use client';

import { Card, Badge } from '@asko/ui';
import { useClickHandlers } from '@/hooks/use-click-handlers';
import type { ScheduleEntry } from './types';
import {
  TYPE_LABELS,
  STATUS_LABELS,
  STATUS_BADGE_VARIANT,
  TYPE_BADGE_VARIANT,
  DAY_LABELS,
  formatDate,
} from './constants';

export function ScheduleCard({
  entry,
  onClick,
  onDoubleClick,
}: {
  entry: ScheduleEntry;
  onClick?: () => void;
  onDoubleClick?: () => void;
}) {
  const { handleClick, handleDoubleClick } = useClickHandlers(onClick, onDoubleClick);

  return (
    <Card
      padding="none"
      className={`p-5 flex flex-col gap-3${onClick || onDoubleClick ? ' cursor-pointer' : ''}`}
      onClick={handleClick}
      onDoubleClick={handleDoubleClick}
    >
      <div className="flex items-center justify-between gap-2">
        <Badge variant={TYPE_BADGE_VARIANT[entry.type] ?? 'neutral'}>
          {TYPE_LABELS[entry.type] ?? entry.type}
        </Badge>
        <Badge variant={STATUS_BADGE_VARIANT[entry.status] ?? 'neutral'}>
          {STATUS_LABELS[entry.status] ?? entry.status}
        </Badge>
      </div>
      <div className="flex flex-col gap-1 text-sm">
        {entry.dayOfWeek != null && entry.dayOfWeek >= 0 && (
          <p className="text-text-main font-medium">{DAY_LABELS[entry.dayOfWeek]}</p>
        )}
        {entry.date && <p className="text-text-main font-medium">{formatDate(entry.date)}</p>}
        <p className="text-text-sub">
          {entry.startTime} — {entry.endTime}
        </p>
        {entry.note && <p className="text-text-sub text-xs truncate">{entry.note}</p>}
      </div>
      {entry.autoGenerated && <p className="text-xs text-text-sub">Автоматически</p>}
    </Card>
  );
}
