'use client';

import { useState } from 'react';
import { Badge, DetailRow, DetailSection } from '@asko/ui';
import { api } from '@/lib/api/client';
import type { ScheduleEntry } from './types';
import {
  TYPE_LABELS,
  STATUS_LABELS,
  STATUS_BADGE_VARIANT,
  TYPE_BADGE_VARIANT,
  formatRange,
} from './constants';
import { formatDate } from '@asko/shared/client';

export async function fetchScheduleOne(item: ScheduleEntry): Promise<ScheduleEntry> {
  const { data } = await api.get<ScheduleEntry>(`/schedule/${item.id}`, { _silent: true } as any);
  return data;
}

export function ScheduleDetail({ item, loading }: { item: ScheduleEntry; loading: boolean }) {
  const [user, setUser] = useState<any>(null);

  const userId = (item as any).userId;

  return (
    <div className="flex flex-col">
      <DetailRow
        label="Тип"
        value={
          <Badge variant={TYPE_BADGE_VARIANT[item.type] ?? 'neutral'}>
            {TYPE_LABELS[item.type] ?? item.type}
          </Badge>
        }
      />
      <DetailRow
        label="Статус"
        value={
          <Badge variant={STATUS_BADGE_VARIANT[item.status] ?? 'neutral'}>
            {STATUS_LABELS[item.status] ?? item.status}
          </Badge>
        }
      />
      <DetailRow label="Период" value={formatRange(item.dateFrom, item.dateTo)} />
      <DetailRow label="Начало" value={item.startTime} />
      <DetailRow label="Конец" value={item.endTime} />
      {item.note && <DetailRow label="Примечание" value={item.note} />}
      <DetailRow label="Автоматически" value={item.autoGenerated ? 'Да' : 'Нет'} />
      <DetailRow label="Создано" value={item.createdAt ? formatDate(item.createdAt) : '-'} />

      {userId && (
        <DetailSection label="Пользователь" summary={user ? [user.lastName, user.firstName].filter(Boolean).join(' ') || user.email || '-' : '-'}
          fetchData={async () => { try { const { data } = await api.post('/users/batch', { ids: [userId] }, { _silent: true } as any); if (data.users?.[0]) setUser(data.users[0]); } catch {} }}>
          {user ? (<>
            <DetailRow label="Имя" value={[user.lastName, user.firstName].filter(Boolean).join(' ') || '-'} />
            {user.email && <DetailRow label="Email" value={user.email} />}
            {user.phone && <DetailRow label="Телефон" value={user.phone} />}
          </>) : <DetailRow label="ID" value={userId} />}
        </DetailSection>
      )}

      {loading && <p className="text-sm text-text-sub py-2">Загрузка...</p>}
    </div>
  );
}
