'use client';

import { Badge } from '@asko/ui';
import { DetailRow } from '@/components/account/shared/detail-row';
import { api } from '@/lib/api/client';
import type { ScheduleEntry } from './types';
import {
  TYPE_LABELS,
  STATUS_LABELS,
  STATUS_BADGE_VARIANT,
  TYPE_BADGE_VARIANT,
  DAY_LABELS,
  formatDate,
} from './constants';

export async function fetchScheduleOne(item: ScheduleEntry): Promise<ScheduleEntry> {
  const { data } = await api.get<ScheduleEntry>(`/schedule/${item.id}`, { _silent: true } as any);
  return data;
}

export function ScheduleDetail({ item, loading }: { item: ScheduleEntry; loading: boolean }) {
  return (
    <div className="flex flex-col">
      <DetailRow
        label="Тип"
        value={
          <Badge variant={TYPE_BADGE_VARIANT[item.type] ?? 'neutral'}>
            {TYPE_LABELS[item.type] ?? item.type}
          </Badge>
        }
      />
      <DetailRow
        label="Статус"
        value={
          <Badge variant={STATUS_BADGE_VARIANT[item.status] ?? 'neutral'}>
            {STATUS_LABELS[item.status] ?? item.status}
          </Badge>
        }
      />
      {item.dayOfWeek != null && item.dayOfWeek >= 0 && (
        <DetailRow label="День недели" value={DAY_LABELS[item.dayOfWeek] ?? '-'} />
      )}
      {item.date && <DetailRow label="Дата" value={formatDate(item.date)} />}
      <DetailRow label="Начало" value={item.startTime} />
      <DetailRow label="Конец" value={item.endTime} />
      {item.note && <DetailRow label="Примечание" value={item.note} />}
      <DetailRow label="Автоматически" value={item.autoGenerated ? 'Да' : 'Нет'} />
      <DetailRow label="Создано" value={item.createdAt ? formatDate(item.createdAt) : '-'} />
      {loading && <p className="text-sm text-text-sub py-2">Загрузка...</p>}
    </div>
  );
}
