export interface ScheduleEntry {
  id: string;
  userId: string;
  type: string;
  dateFrom: string;
  dateTo: string;
  startTime: string;
  endTime: string;
  status: string;
  approvedBy?: string;
  note?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PatternSlot {
  work: boolean;
  startTime?: string | null;
  endTime?: string | null;
}

export interface PatternRecord {
  id: string;
  userId: string;
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlot[];
  createdAt: string;
  updatedAt: string;
}

export interface PatternUpsertInput {
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlot[];
}
