export interface ScheduleEntry {
  type: string;
  id: string;
  userId: string;
  dateFrom: string;
  dateTo: string;
  startTime: string;
  endTime: string;
  durationDays?: number;
  status: string;
  createdBy?: string;
  approvedBy?: string;
  note?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PatternSlot {
  work: boolean;
  startTime?: string | null;
  endTime?: string | null;
}

export interface PatternPending {
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlot[];
}

export interface PatternRecord {
  id: string;
  userId: string;
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlot[];
  createdAt: string;
  updatedAt: string;
  status?: string;
  approvedBy?: string;
  approvedAt?: string;
  pendingData?: PatternPending | null;
  hasPendingData?: boolean;
}

export interface PatternUpsertInput {
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlot[];
}
