services:

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.payment-service
    container_name: asko-payment-service
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_ENV: production
      GRPC_PORT: 5001

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user-service
    container_name: asko-user-service
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_ENV: production
      GRPC_PORT: 5000

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: asko-api
    restart: unless-stopped
    network_mode: host
    depends_on:
      - user-service
      - payment-service
    environment:
      NODE_ENV: production
      USER_SERVICE_URL: "localhost:5000"
      PAYMENT_SERVICE_URL: "localhost:5001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: asko-web
    restart: unless-stopped
    network_mode: host
    depends_on:
      - api
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
