services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: asko-api
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: asko-web
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
