FROM node:20-alpine AS base
RUN corepack enable

# ---------- deps ----------
FROM base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc turbo.json tsconfig.json ./

COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
COPY packages/shared/package.json ./packages/shared/
COPY packages/ui/package.json ./packages/ui/

RUN pnpm install --frozen-lockfile


# ---------- builder ----------
FROM base AS builder
WORKDIR /app

COPY --from=deps /app ./

COPY packages/shared ./packages/shared
COPY apps/api ./apps/api

COPY apps/api/.env.prod ./apps/api/.env.prod

RUN pnpm --filter @asko/shared build
RUN pnpm --filter api build


# ---------- prod deps ----------
FROM base AS prod-deps
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

COPY apps/api/package.json ./apps/api/
COPY packages/shared/package.json ./packages/shared/

RUN pnpm install --prod --frozen-lockfile


# ---------- runner ----------
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=prod-deps /app/package.json ./

COPY --from=builder /app/packages/shared/dist ./packages/shared/dist
COPY --from=builder /app/packages/shared/package.json ./packages/shared/package.json

COPY --from=builder /app/apps/api/dist ./apps/api/dist
COPY --from=builder /app/apps/api/package.json ./apps/api/package.json

COPY apps/api/images ./apps/api/images
COPY apps/api/.env.prod ./apps/api/.env.prod

WORKDIR /app/apps/api

EXPOSE 4000

CMD ["node", "dist/src/main.js"]
