FROM node:20-alpine AS base
RUN corepack enable


# ---------- deps ----------
FROM base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc turbo.json tsconfig.json ./

COPY apps/web/package.json ./apps/web/
COPY packages/shared/package.json ./packages/shared/
COPY packages/ui/package.json ./packages/ui/

RUN pnpm install --frozen-lockfile


# ---------- builder ----------
FROM base AS builder
WORKDIR /app

COPY --from=deps /app ./

COPY packages/shared ./packages/shared
COPY packages/ui ./packages/ui
COPY apps/web ./apps/web

COPY apps/web/.env.prod ./apps/web/.env.prod

RUN pnpm --filter @asko/shared build
RUN pnpm --filter @asko/ui build
RUN pnpm --filter @asko/web build


# ---------- runner ----------
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/apps/web/public ./apps/web/public

COPY apps/web/.env.prod ./apps/web/.env.prod

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["node", "server.js"]
