services:

  api:
    image: ghcr.io/yolona-oss/asko-rsw/api:latest
    container_name: asko-api
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    image: ghcr.io/yolona-oss/asko-rsw/web:latest
    container_name: asko-web
    restart: unless-stopped
    network_mode: host
    depends_on:
      - api
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
