FROM node:20-alpine AS base
RUN corepack enable
WORKDIR /app


# ---------- prune ----------
FROM base AS prune

COPY . .

RUN pnpm dlx turbo prune api --docker


# ---------- deps ----------
FROM base AS deps

COPY --from=prune /app/out/json/ .
COPY --from=prune /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=prune /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY .npmrc .npmrc

RUN pnpm install --frozen-lockfile


# ---------- build ----------
FROM base AS builder

COPY --from=deps /app ./
COPY --from=prune /app/out/full/ .

RUN pnpm turbo run build --filter=api...


# ---------- prod deps ----------
FROM base AS prod-deps

COPY --from=prune /app/out/json/ .
COPY --from=prune /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=prune /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY .npmrc .npmrc

RUN pnpm install --prod --frozen-lockfile


# ---------- runner ----------
FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY --from=prod-deps /app/node_modules ./node_modules

COPY --from=builder /app/apps/api/dist ./apps/api/dist
COPY --from=builder /app/packages/shared/dist ./packages/shared/dist

COPY apps/api/images ./apps/api/images
COPY apps/api/.env.prod ./apps/api/.env.prod

WORKDIR /app/apps/api

CMD ["node", "dist/src/main.js"]
