services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: asko-rabbitmq-dev
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: asko-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
