import { api } from './client';

export interface ScheduleRecord {
  id: string;
  userId: string;
  type: string;
  dayOfWeek?: number;
  date?: string;
  startTime: string;
  endTime: string;
  status: string;
  approvedBy?: string;
  note?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedSchedules {
  data: ScheduleRecord[];
  overallCount: number;
  page: number;
  limit: number;
}

export const scheduleApi = {
  getAll(params?: {
    page?: number;
    limit?: number;
    userId?: string;
    type?: string;
    status?: string;
    dateFrom?: string;
    dateTo?: string;
    sortBy?: string;
    sortOrder?: string;
  }) {
    return api.get<PaginatedSchedules>('/schedule', { params });
  },

  getOne(id: string) {
    return api.get<ScheduleRecord>(`/schedule/${id}`);
  },

  getWeekly(userId: string) {
    return api.get<ScheduleRecord[]>(`/schedule/weekly/${userId}`);
  },

  create(data: {
    userId: string;
    type: string;
    dayOfWeek?: number;
    date?: string;
    startTime: string;
    endTime: string;
    note?: string;
  }) {
    return api.post<ScheduleRecord>('/schedule', data);
  },

  update(id: string, data: {
    type?: string;
    dayOfWeek?: number | null;
    date?: string | null;
    startTime?: string;
    endTime?: string;
    status?: string;
    note?: string | null;
  }) {
    return api.put<ScheduleRecord>(`/schedule/${id}`, data);
  },

  delete(id: string) {
    return api.delete(`/schedule/${id}`);
  },

  approve(id: string) {
    return api.post<ScheduleRecord>(`/schedule/${id}/approve`);
  },

  reject(id: string) {
    return api.post<ScheduleRecord>(`/schedule/${id}/reject`);
  },
};
