import { api } from './client';

export interface ScheduleRecord {
  id: string;
  userId: string;
  type: string;
  dateFrom: string;
  dateTo: string;
  startTime: string;
  endTime: string;
  status: string;
  approvedBy?: string;
  note?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedSchedules {
  data: ScheduleRecord[];
  overallCount: number;
  page: number;
  limit: number;
}

export interface PatternSlotDto {
  work: boolean;
  startTime?: string | null;
  endTime?: string | null;
}

export interface PatternRecordDto {
  id: string;
  userId: string;
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlotDto[];
  createdAt: string;
  updatedAt: string;
}

export interface UpsertPatternInput {
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlotDto[];
}

export const scheduleApi = {
  getAll(params?: {
    page?: number;
    limit?: number;
    userId?: string;
    type?: string;
    status?: string;
    dateFrom?: string;
    dateTo?: string;
    sortBy?: string;
    sortOrder?: string;
  }) {
    return api.get<PaginatedSchedules>('/schedule', { params });
  },

  getOne(id: string) {
    return api.get<ScheduleRecord>(`/schedule/${id}`);
  },

  create(data: {
    userId: string;
    type: string;
    dateFrom: string;
    dateTo: string;
    startTime: string;
    endTime: string;
    note?: string;
  }) {
    return api.post<ScheduleRecord>('/schedule', data);
  },

  createVacation(data: {
    userId: string;
    dateFrom: string;
    dateTo: string;
    note?: string;
  }) {
    return api.post<ScheduleRecord>('/schedule/vacation', data);
  },

  update(id: string, data: {
    type?: string;
    dateFrom?: string;
    dateTo?: string;
    startTime?: string;
    endTime?: string;
    status?: string;
    note?: string | null;
  }) {
    return api.put<ScheduleRecord>(`/schedule/${id}`, data);
  },

  delete(id: string) {
    return api.delete(`/schedule/${id}`);
  },

  approve(id: string) {
    return api.post<ScheduleRecord>(`/schedule/${id}/approve`);
  },

  reject(id: string) {
    return api.post<ScheduleRecord>(`/schedule/${id}/reject`);
  },

  patternGet(userId: string) {
    return api.get<PatternRecordDto | null>(`/schedule/pattern/${userId}`);
  },

  patternUpsert(userId: string, data: UpsertPatternInput) {
    return api.put<PatternRecordDto>(`/schedule/pattern/${userId}`, data);
  },

  patternDelete(userId: string) {
    return api.delete(`/schedule/pattern/${userId}`);
  },

  patternGetMany(userIds: string[]) {
    return api.get<{ data: PatternRecordDto[] }>('/schedule/patterns', {
      params: { userIds: userIds.join(',') },
    });
  },
};
