import { api } from './client';

export interface ScheduleRecord {
  id: string;
  userId: string;
  type: string;
  dateFrom: string;
  dateTo: string;
  startTime: string;
  endTime: string;
  status: string;
  approvedBy?: string;
  note?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedSchedules {
  data: ScheduleRecord[];
  overallCount: number;
  page: number;
  limit: number;
}

export interface PatternSlotDto {
  work: boolean;
  startTime?: string | null;
  endTime?: string | null;
}

export interface PatternPendingDto {
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlotDto[];
}

export interface PatternRecordDto {
  id: string;
  userId: string;
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlotDto[];
  createdAt: string;
  updatedAt: string;
  status?: string;
  approvedBy?: string;
  approvedAt?: string;
  pendingData?: PatternPendingDto | null;
  hasPendingData?: boolean;
}

export interface PatternHistoryRecord {
  id: string;
  patternId: string;
  userId: string;
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlotDto[];
  status: string;
  pendingData?: PatternPendingDto;
  changeType: string;
  changedBy?: string;
  isActive: boolean;
  effectiveFrom: string;
  changedAt: string;
}

export interface PaginatedPatternHistory {
  data: PatternHistoryRecord[];
  overallCount: number;
  page: number;
  limit: number;
}

export interface ScheduleAggregateReport {
  userId: string;
  dateFrom: string;
  dateTo: string;
  isCurrentlyActive: boolean;
  totalDays: number;
  activeDays: number;
  inactiveDays: number;
  workDays: number;
  restDays: number;
  noPatternDays: number;
  vacationDays: number;
  sickLeaveDays: number;
  overtimeCount: number;
  overtimeTotalMinutes: number;
  extraDayCount: number;
  patternRevisions: number;
}

export interface UpsertPatternInput {
  cycleLength: number;
  anchorDate: string;
  defaultStartTime: string;
  defaultEndTime: string;
  slots: PatternSlotDto[];
}

export const scheduleApi = {
  getAll(params?: {
    page?: number;
    limit?: number;
    userId?: string;
    type?: string;
    status?: string;
    dateFrom?: string;
    dateTo?: string;
    sortBy?: string;
    sortOrder?: string;
  }) {
    return api.get<PaginatedSchedules>('/schedule', { params });
  },

  getOne(id: string) {
    return api.get<ScheduleRecord>(`/schedule/${id}`);
  },

  create(data: {
    userId: string;
    type: string;
    dateFrom: string;
    dateTo: string;
    startTime: string;
    endTime: string;
    note?: string;
  }) {
    return api.post<ScheduleRecord>('/schedule', data);
  },

  createVacation(data: {
    userId: string;
    dateFrom: string;
    dateTo: string;
    note?: string;
  }) {
    return api.post<ScheduleRecord>('/schedule/vacation', data);
  },

  update(id: string, data: {
    type?: string;
    dateFrom?: string;
    dateTo?: string;
    startTime?: string;
    endTime?: string;
    status?: string;
    note?: string | null;
  }) {
    return api.put<ScheduleRecord>(`/schedule/${id}`, data);
  },

  delete(id: string) {
    return api.delete(`/schedule/${id}`);
  },

  approve(id: string) {
    return api.post<ScheduleRecord>(`/schedule/${id}/approve`);
  },

  reject(id: string) {
    return api.post<ScheduleRecord>(`/schedule/${id}/reject`);
  },

  patternGet(userId: string) {
    return api.get<PatternRecordDto | null>(`/schedule/pattern/${userId}`);
  },

  patternUpsert(userId: string, data: UpsertPatternInput) {
    return api.put<PatternRecordDto>(`/schedule/pattern/${userId}`, data);
  },

  patternDelete(userId: string) {
    return api.delete(`/schedule/pattern/${userId}`);
  },

  patternGetMany(userIds: string[]) {
    return api.get<{ data: PatternRecordDto[] }>('/schedule/patterns', {
      params: { userIds: userIds.join(',') },
    });
  },

  patternApprove(userId: string) {
    return api.post<PatternRecordDto>(`/schedule/pattern/${userId}/approve`);
  },

  patternReject(userId: string) {
    return api.post<PatternRecordDto>(`/schedule/pattern/${userId}/reject`);
  },

  patternHistory(userId: string, params?: { dateFrom?: string; dateTo?: string; page?: number; limit?: number }) {
    return api.get<PaginatedPatternHistory>(`/schedule/pattern/${userId}/history`, { params });
  },

  scheduleReport(userId: string, dateFrom: string, dateTo: string) {
    return api.get<ScheduleAggregateReport>(`/schedule/report/${userId}`, { params: { dateFrom, dateTo } });
  },
};
