apiVersion: v1
kind: Secret
metadata:
  name: asko-secrets
  namespace: asko
type: Opaque
stringData:
  JWT_ACCESS_PUBLIC_KEY: "<base64-encoded>"
  JWT_ACCESS_PRIVATE_KEY: "<base64-encoded>"
  JWT_REFRESH_SECRET: "<secret>"
  DB_PASSWORD: "<password>"
  RABBITMQ_PASS: "<rmq-password>"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  VK_CLIENT_ID: ""
  VK_CLIENT_SECRET: ""
  YANDEX_CLIENT_ID: ""
  YANDEX_CLIENT_SECRET: ""
