export enum NotificationType {
    REPAIR_STATUS_CHANGED = 'repair_status_changed',
    REPAIR_ASSIGNED = 'repair_assigned',
    REPAIR_TRANSFERRED_TO_REPAIRER = 'repair_transferred_to_repairer',
    REPAIR_TRANSFERRED_FROM_REPAIRER = 'repair_transferred_from_repairer',
    REPAIR_TRANSFERRED_CLIENT = 'repair_transferred_client',
    REPAIR_DIAGNOSTICS_DECLINED = 'repair_diagnostics_declined',
    REPAIR_COMPLETED = 'repair_completed',
    INVOICE_CREATED = 'invoice_created',
    PAYMENT_PAID = 'payment_paid',
    PAYMENT_FAILED = 'payment_failed',
    PAYMENT_REFUNDED = 'payment_refunded',
    INVOICE_UNPAID_REMINDER = 'invoice_unpaid_reminder',
    REPAIR_ASSIGNMENT_REMINDER = 'repair_assignment_reminder',
    REPAIR_IN_PROGRESS_STUCK = 'repair_in_progress_stuck',
    CERTIFICATE_ISSUED = 'certificate_issued',
    CERTIFICATE_EXPIRING_SOON = 'certificate_expiring_soon',
    CERTIFICATE_EXPIRED = 'certificate_expired',
    CHAT_MESSAGE = 'chat_message',
    CHAT_CONVERSATION_CREATED = 'chat_conversation_created',
    CHAT_PARTICIPANT_ADDED = 'chat_participant_added',
    CHAT_PARTICIPANT_REMOVED = 'chat_participant_removed',
    MESSAGE = 'message',
    SYSTEM = 'system',
    SCHEDULE_CREATED = 'schedule_created',
    SCHEDULE_APPROVED = 'schedule_approved',
    SCHEDULE_REJECTED = 'schedule_rejected',
    SCHEDULE_UPDATED = 'schedule_updated',
    SCHEDULE_DELETED = 'schedule_deleted',
    SCHEDULE_EXTRA_DAY_REQUESTED = 'schedule_extra_day_requested',
    SCHEDULE_EXTRA_DAY_ACCEPTED = 'schedule_extra_day_accepted',
    SCHEDULE_EXTRA_DAY_REJECTED = 'schedule_extra_day_rejected',
    SCHEDULE_PATTERN_CREATED = 'schedule_pattern_created',
    SCHEDULE_PATTERN_UPDATED = 'schedule_pattern_updated',
    SCHEDULE_PATTERN_DELETED = 'schedule_pattern_deleted',
    SCHEDULE_PATTERN_APPROVED = 'schedule_pattern_approved',
    SCHEDULE_PATTERN_REJECTED = 'schedule_pattern_rejected',
    AVR_SIGNING_REQUESTED = 'avr_signing_requested',
    AVR_SIGNED = 'avr_signed',
    ADDRESS_VALIDATED = 'address_validated',
    ADDRESS_VALIDATION_FAILED = 'address_validation_failed',
    USER_DEVICE_VALIDATED = 'user_device_validated',
    USER_DEVICE_VALIDATION_FAILED = 'user_device_validation_failed',
}

export enum NotificationTargetType {
    REPAIR_REQUEST = 'repairRequest',
    PAYMENT = 'payment',
    CERTIFICATE = 'certificate',
    CONVERSATION = 'conversation',
    SCHEDULE = 'schedule',
    ADDRESS = 'address',
    USER_DEVICE = 'userDevice',
    SYSTEM = 'system',
}
