export enum NotificationType {
    REPAIR_STATUS_CHANGED = 'repair_status_changed',
    REPAIR_ASSIGNED = 'repair_assigned',
    REPAIR_TRANSFERRED_TO_REPAIRER = 'repair_transferred_to_repairer',
    REPAIR_TRANSFERRED_FROM_REPAIRER = 'repair_transferred_from_repairer',
    REPAIR_TRANSFERRED_CLIENT = 'repair_transferred_client',
    REPAIR_DIAGNOSTICS_DECLINED = 'repair_diagnostics_declined',
    REPAIR_COMPLETED = 'repair_completed',
    PAYMENT_PAID = 'payment_paid',
    PAYMENT_FAILED = 'payment_failed',
    PAYMENT_REFUNDED = 'payment_refunded',
    CERTIFICATE_ISSUED = 'certificate_issued',
    CERTIFICATE_EXPIRING_SOON = 'certificate_expiring_soon',
    CERTIFICATE_EXPIRED = 'certificate_expired',
    CHAT_MESSAGE = 'chat_message',
    CHAT_CONVERSATION_CREATED = 'chat_conversation_created',
    CHAT_PARTICIPANT_ADDED = 'chat_participant_added',
    CHAT_PARTICIPANT_REMOVED = 'chat_participant_removed',
    MESSAGE = 'message',
    SYSTEM = 'system',
    SCHEDULE_CREATED = 'schedule_created',
    SCHEDULE_APPROVED = 'schedule_approved',
    SCHEDULE_REJECTED = 'schedule_rejected',
    SCHEDULE_UPDATED = 'schedule_updated',
}

export enum NotificationTargetType {
    REPAIR_REQUEST = 'repairRequest',
    PAYMENT = 'payment',
    CERTIFICATE = 'certificate',
    CONVERSATION = 'conversation',
    SCHEDULE = 'schedule',
    SYSTEM = 'system',
}
