export enum ScheduleEntryType {
    WORK = 'work',
    VACATION = 'vacation',
    SICK_LEAVE = 'sick_leave',
    OVERTIME = 'overtime',
    EXTRA_DAY = 'extra_day',
}

export enum ScheduleStatus {
    PENDING = 'pending',
    APPROVED = 'approved',
    REJECTED = 'rejected',
}

export interface IScheduleEntry {
    id: string;
    userId: string;
    type: ScheduleEntryType;
    dayOfWeek?: number | null;
    date?: string | null;
    startTime: string;
    endTime: string;
    status: ScheduleStatus;
    approvedBy?: string | null;
    note?: string | null;
    autoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}
