export enum ScheduleEntryType {
    VACATION = 'vacation',
    SICK_LEAVE = 'sick_leave',
    OVERTIME = 'overtime',
    SCHEDULE_OVERRIDE = 'schedule_override',
}

export enum ScheduleStatus {
    PENDING = 'pending',
    APPROVED = 'approved',
    REJECTED = 'rejected',
}

export interface IVacation {
    id: string;
    userId: string;
    dateFrom: string;
    durationDays: number;
    dateTo: string;
    status: ScheduleStatus;
    createdBy?: string | null;
    approvedBy?: string | null;
    note?: string | null;
    createdAt: string;
    updatedAt: string;
}

export interface ISickLeave {
    id: string;
    userId: string;
    dateFrom: string;
    durationDays: number;
    dateTo: string;
    status: ScheduleStatus;
    createdBy?: string | null;
    approvedBy?: string | null;
    note?: string | null;
    createdAt: string;
    updatedAt: string;
}

export interface IOvertime {
    id: string;
    userId: string;
    date: string;
    startTime: string;
    endTime: string;
    status: ScheduleStatus;
    createdBy?: string | null;
    approvedBy?: string | null;
    note?: string | null;
    autoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface IScheduleOverride {
    id: string;
    userId: string;
    date: string;
    startTime: string;
    endTime: string;
    status: ScheduleStatus;
    createdBy?: string | null;
    approvedBy?: string | null;
    note?: string | null;
    autoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface IScheduleEntry {
    type: ScheduleEntryType;
    id: string;
    userId: string;
    dateFrom: string;
    dateTo: string;
    startTime: string;
    endTime: string;
    durationDays?: number;
    status: ScheduleStatus;
    createdBy?: string | null;
    approvedBy?: string | null;
    note?: string | null;
    autoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface IPatternSlot {
    work: boolean;
    startTime?: string | null;
    endTime?: string | null;
}

export interface ISchedulePattern {
    id: string;
    userId: string;
    cycleLength: number;
    anchorDate: string;
    defaultStartTime: string;
    defaultEndTime: string;
    slots: IPatternSlot[];
    createdAt: string;
    updatedAt: string;
}
