apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-data
  namespace: asko
  labels:
    app: file-service
    component: infra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
